//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imobi.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imobi.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é inválida!.
        /// </summary>
        public static string Generico_Invalida_0X {
            get {
                return ResourceManager.GetString("Generico_Invalida_0X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é inválido!.
        /// </summary>
        public static string Generico_Invalido_0X {
            get {
                return ResourceManager.GetString("Generico_Invalido_0X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} deve ter entre {1} e {2} caracteres.
        /// </summary>
        public static string Generico_MinMax_0X_A {
            get {
                return ResourceManager.GetString("Generico_MinMax_0X_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ter entre {1} e {2} caracteres.
        /// </summary>
        public static string Generico_MinMax_0X_O {
            get {
                return ResourceManager.GetString("Generico_MinMax_0X_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não encontrado!.
        /// </summary>
        public static string Generico_Nao_Encontrado_0X {
            get {
                return ResourceManager.GetString("Generico_Nao_Encontrado_0X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório!.
        /// </summary>
        public static string Generico_Obrigatorio_0X {
            get {
                return ResourceManager.GetString("Generico_Obrigatorio_0X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação realizada com sucesso!.
        /// </summary>
        public static string Generico_Operacao_Realizada_Com_Sucesso {
            get {
                return ResourceManager.GetString("Generico_Operacao_Realizada_Com_Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Generico_Titulo_Email {
            get {
                return ResourceManager.GetString("Generico_Titulo_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Generico_Titulo_Senha {
            get {
                return ResourceManager.GetString("Generico_Titulo_Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível alterar os dados do usuário, pois ele está desativado!.
        /// </summary>
        public static string Usuario_Alterar_Erro_Status {
            get {
                return ResourceManager.GetString("Usuario_Alterar_Erro_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        public static string Usuario_Primeiro_Nome {
            get {
                return ResourceManager.GetString("Usuario_Primeiro_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Usuario_SobreNome_Nome {
            get {
                return ResourceManager.GetString("Usuario_SobreNome_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario_Title {
            get {
                return ResourceManager.GetString("Usuario_Title", resourceCulture);
            }
        }
    }
}
