//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imobiliaria.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imobiliaria.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Houve um erro ao gerar o comodo. Entre em contato com o time Imobi..
        /// </summary>
        public static string Comodo_Criar_ErroGenerico {
            get {
                return ResourceManager.GetString("Comodo_Criar_ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! A data {0} é menor que a data atual!.
        /// </summary>
        public static string Comum_Erro_Data_MenorQueAtual {
            get {
                return ResourceManager.GetString("Comum_Erro_Data_MenorQueAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Houve um erro ao gerar a medição. Entre em contato com o time Imobi..
        /// </summary>
        public static string Medicao_Criar_ErroGenerico {
            get {
                return ResourceManager.GetString("Medicao_Criar_ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Houve um erro ao gerar um nota. Entre em contato com o time Imobi..
        /// </summary>
        public static string Nota_Criar_ErroGenerico {
            get {
                return ResourceManager.GetString("Nota_Criar_ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Solicitação:.
        /// </summary>
        public static string Titulo_DataSolicitacao {
            get {
                return ResourceManager.GetString("Titulo_DataSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitador Inválido!.
        /// </summary>
        public static string Usuario_Erro_SolicitadorInvalido {
            get {
                return ResourceManager.GetString("Usuario_Erro_SolicitadorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistoriador Inválido!.
        /// </summary>
        public static string Usuario_Erro_VistoriadorInvalido {
            get {
                return ResourceManager.GetString("Usuario_Erro_VistoriadorInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ops! Houve um erro ao gerar a vistoria. Entre em contato com o time Imobi..
        /// </summary>
        public static string Vistoria_Criar_ErroGenerico {
            get {
                return ResourceManager.GetString("Vistoria_Criar_ErroGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Vistoria.
        /// </summary>
        public static string Vistoria_DataVistoria {
            get {
                return ResourceManager.GetString("Vistoria_DataVistoria", resourceCulture);
            }
        }
    }
}
