// <auto-generated />
using System;
using Imobi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Imobi.Migrations
{
    [DbContext(typeof(ImobiContext))]
    partial class ImobiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Imobi.Models.ViewModels.Teste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("VistoriaDescricao");

                    b.HasKey("Id");

                    b.ToTable("Teste");
                });

            modelBuilder.Entity("Imobi.Models.ViewModels.Vistoria.Vistoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Agua");

                    b.Property<DateTime>("DataVistoria");

                    b.Property<bool>("Energia");

                    b.Property<bool>("Gas");

                    b.Property<long>("IdSolicitacao");

                    b.Property<string>("Nome");

                    b.Property<string>("Observacao");

                    b.Property<byte>("Status");

                    b.HasKey("Id");

                    b.ToTable("Vistoria");
                });
#pragma warning restore 612, 618
        }
    }
}
